[
('result', 'Pantun bertema situasi', 'Ada kijang berjalan di hutan\nSampailah ia ke kebun kosong\nAda seorang bujang berlarian\nKarena dengar anjing menggonggong.'),
('result', 'Pantun lucu gombalan', 'Aku sedang minum jamu\nMinumnya di bawah pohon jambu\nAku tak mau kehilangan kamu\nKarna ku sangat mencintaimu.'),
('result', 'Pantun humor romantis', 'Aku tuh suka banget minum jamu\nApalagi minumnya dibawah pohon jambu\nAku tuh gak mau kehilangan kamu\nKarna aku sangat mencintaimu.'),
('result', 'Pantun lucu humor', 'Anak-anak bersuka ria\nBermain menari berdendang pula\nOrang mana yang tak kan tertawa\nDisangka waras tapi ternyata gila.'),
('result', 'Pantun lucu galau', 'Beli ikan di Belgia\nDi buka dan dibagi rata\nAkan ku berikan kau bahagia\nTanpa luka dan air mata.'),
('result', 'Pantun lucu gombalan', 'Beli kain warna merah\nDari kediri pakenya batik\nDigodain jangan marah\nSalah sendiri punya wajah cantik.'),
('result', 'Pantun bertema situasi', 'Beras ditanak jadilah nasi\nAyam goreng enak baunya\nCukup siapkan piring sebiji\nLebih enak makan bersama.'),
('result', 'Pantun humor random', 'Berteduh di bawah pohon memiliki dahan\nMeski sederhana kelihatan mewahnya\nIni pantun lucu tentang kebersihan\nWalau bercanda ada manfaatnya.'),
('result', 'Pantun lucu ejekan', 'Buah kesemek buah tomat\nDisimpan di dalam lemari\nPantas dari tadi bau menyengat\nTernyata kau belum mandi.'),
('result', 'Pantun lucu gombalan', 'Buah salak baru dipetik\nBuah duku buah delima\nAda banyak wanita cantik\nCuma kamu yang aku cinta.'),
('result', 'Pantun lucu galau', 'Bulan purnama begitu menggoda\nAir di danau beriak-riak bahagia\nMeski rindu kadang menyiksa\nAku tetap akan setia.'),
('result', 'Pantun bertema situasi', 'Bunga mawar bertangkai duri\nLaris manis berdagang cendol\nAku sungguh malu sekali\nTiap ingat dulu suka ngompol.'),
('result', 'Pantun lucu galau', 'Burung elang makanya nasi\nBurung kutilang suaranya merdu\nDuhai sayang pujaan hati\nAbang kangen dan sangat rindu.'),
('result', 'Pantun lucu gombalan', 'Burung gelatik di atas nampan\nPaling enak dijadikan pancingan\nKamu cantik aku tampan\nCocok banget kali jadian.'),
('result', 'Pantun kocak nasehat', 'Cari kerja sesungguhnya susah\napalagi tidak ada keahlian\ntapi banyak termasuk mudah\nmemang lah malas cari makan.'),
('result', 'Pantun kocak nasehat', 'Carilah harta yg halal\nagar anak istri tidak jalal\nkalau mengemis membuat mu sial\njangan berbohong lantaran kenal.'),
('result', 'Pantun lucu ejekan', 'Dari pada di rumah saja menganggur\nLebih baik jualan sate kerang\nRezeki itu sudah ada yang mengatur\nJangan iri melihat suksesnya orang.'),
('result', 'Pantun humor random', 'Di hari kurban memotong kambing\nSaling berbagi kepada tetangga\nJangan sedih beristri sumbing\nKarena kalau marah seperti tertawa.'),
('result', 'Pantun humor cinta', 'Disana gunung di sini gunung\nTengah – tengahnya pohonnya jati\nBetapa hatiku tengah terbingung\nMenunggunya jawaban sijantung hati.'),
('result', 'Pantun lucu humor', 'Duduk di atap si kucing betina\nTak hentinya mengeong-ngeong\nKulihat wanita cantik jelita\nMalang melanda punggungnya bolong.'),
('result', 'Pantun bertema kasmaran', 'Es doger rasanya segar\nBuat camilan makan telur asin\nAdek manis cepatlah besar\nBiar segera abang nikahin.'),
('result', 'Pantun jenaka anak anak', 'Harimau telah semakin sombong\nSuka menghina yang jelak\nMasih kecil telah ompong\nMirip bersama dengan nenek-nenek.'),
('result', 'Pantun lucu ejekan', 'Hati-hati kalau meludah\nJangan sampai kena sepatu orang\nMinta maaf itu memang mudah\nTapi tak guna jika masih diulang.'),
('result', 'Pantun humor random', 'Hendak wisata ke kota tua\nBeli ikan si ikan sepat\nTak apa dapat istri tua\nUdah penyayang pengalaman udah didapat.'),
('result', 'Pantun jenaka pendidikan', 'Hendaklah melempar jangkar\nKalau ada perahu singgah\nKalau anak bangsa pintar\nNegeri ini dapat bangga.'),
('result', 'Pantun kocak nasehat', 'Hidup bukanlah untuk makan\ntapi hidup memiliki tujuan\nkalau makan sebagai kehidupan\nserupalah bersama dengan sang hewan.'),
('result', 'Pantun kocak sindiran', 'Hidup senang karena iman\nNafsu maksiat bakal terkekang\nBagaimana disebut teman\nDia menusuk dari belakang.'),
('result', 'Pantun lucu galau', 'Jalan pagi-pagi\nJangan lupa ngajak santri\nWalau kita tidak bersama lagi\nTapi kau kan selalu di hati.'),
('result', 'Pantun lucu gombalan', 'Jalan-jalan ke Kota Prancis\nBanyak rumah berbaris-baris\nBiar mati diujung keris\nAsal dapat adinda yang manis.'),
('result', 'Pantun bertema kehidupan', 'Jalan-jalan ke pantai Indrayanti\nJangan lupa membawa sepeda\nTak guna menanti nasib tak pasti\nKalau tak pernah mau berusaha.'),
('result', 'Pantun humor romantis', 'Jalan-jalan ke Samarinda\nTidak lupa bawa bambu\nMakin lama makin bahagia\nLihat kamu berkerudung ungu.'),
('result', 'Pantun bertema kasmaran', 'Jalan-jalan ke Sumedang\nPulangnya mampir pasar malam\nAda abang rajin sembahyang\nMau dong jadikan dia imam.'),
('result', 'Pantun bertema situasi', 'Jalan-jalan lewat pinggir empang\nDi pinggir empang nemu kotak\nHati siapa yang tak jadi bimbang\nMinta dikepang padahal dia botak.'),
('result', 'Pantun kocak sindiran', 'Jalan-jalan naik delman\nKeliling kota hingga senja\nTeman mengaku teman\nKalau tersedia maunya saja.'),
('result', 'Pantun lucu humor', 'Jalan-jalan sampai Lamongan\nJangan lupa jajan soto\nSwadaya sudah lagi tak zaman\nYang ada sekarang adalah swafoto.'),
('result', 'Pantun jenaka anak anak', 'Jari sakit dikarenakan luka\nLukanya sangatlah besar\nIni contoh pantun jenaka\nUntuk anak sekolah dasar.'),
('result', 'Pantun jenaka pendidikan', 'Jika hendak anda melamar\nJangan banyak tulis dihapus\nJika siswa rajin belajar\nSudah pasti pasti lulus.'),
('result', 'Pantun jenaka pendidikan', 'Jika kita pegang kuas\nMelukislah pada kertas\nJika anak bangsa cerdas\nBangsa pun berkualitas.'),
('result', 'Pantun bertema kehidupan', 'Jual kelapa laku sepuluh\nSisanya akan dikirim ke Padang\nSusah nian punya anak sepuluh\nTidur seperti ikan pindang.'),
('result', 'Pantun kocak nasehat', 'Kalau emas dikata suasa\ntentu kuningan seperti tembaga\nkalau tidak rela berusaha\nmeminta mintalah kerjanya.'),
('result', 'Pantun lucu ejekan', 'Kalau memang gigi sudah ompong\nSegeralah pergi ke dokter gigi\nJangan jadi anak yang sombong\nPasti kan rugi di kemudian hari.'),
('result', 'Pantun jenaka anak anak', 'Kancil cari undur-undur\nMencarinya muter-muter\nAda anak suka tidur\nSambil ngorok sambil ngiler.'),
('result', 'Pantun jenaka pendidikan', 'Kehutan mencari rusa\nHendaklah mempunyai tali\nWahai anak-anak bangsa\nCepat bangun lekas mandi.'),
('result', 'Pantun bertema kehidupan', 'Kenapa mau panen kelapa\nPadahal belum tumbuh tunas\nKenapa mau beli vespa\nPadahal cicilan kompor saja belum lunas.'),
('result', 'Pantun kocak sindiran', 'Kunang-kunang berlaksa-laksa\nDi selagi hujan badannya basah\nPinjam duwit 1/2 memaksa\nBayar hutangnya benar-benar susah.'),
('result', 'Pantun jenaka anak anak', 'Lebar sekali daun talas\nUntuk menaikkan daun talam\nMakanya jangan suka malas\nSikat gigi pagi dan malam.'),
('result', 'Pantun lucu humor', 'Makan roti tawar pakai Nutella\nTapi ternyata kalengnya kosong\nGadis kecil melongok ke jendela\nMemamerkan giginya yang ompong.'),
('result', 'Pantun lucu gombalan', 'Malam minggu jalan ama pacar\nDia pakai baju biru\nCintaku padamu amatlah besar\nKarena separuh aku darimu.'),
('result', 'Pantun lucu ejekan', 'Malam-malam gelap gulita\nMenyalakan pelita diisi minyak\nWajahmu memang cantik jelita\nayang tertawanya mirip kuntilanak.'),
('result', 'Pantun bertema kasmaran', 'Membeli kain berwarna merah\nDari Kediri memakai batik\nEneng digoda janganlah marah\nSalah eneng punya wajah cantik.'),
('result', 'Pantun humor cinta', 'Meminum jamu sambilah berdiri\nDi seduhnya cepat berduduk dibangku\nBilanya hati kamu masi sendiri\nBerikanlah area untuk diri aku.'),
('result', 'Pantun humor romantis', 'Meskipun hanya buah jambu\nTapi ini bisa diramu\nMeskipun jarang bertemu\nCintaku hanya untukmu.'),
('result', 'Pantun humor cinta', 'Naik keatap memakai lamborjini\nlamborjini bekas pakain pita\nCobalah tatap mata aku ini\naKan engkau bisa satu berkas cinta.'),
('result', 'Pantun kocak sindiran', 'Pagi hari tanam bawang\nAda ular berkelat kelit\nSeringkali minjam uang\nGiliran dipinjam benar-benar pelit.'),
('result', 'Pantun humor romantis', 'Pagi-pagi udah sarapan\nLauknya ikan teri\nMet pagi aku ucapkan\nUntukmu kekasih hati.'),
('result', 'Pantun lucu galau', 'Pakai sepatu warnanya merah\nRasanya nyaman walau tak baru\nHati rindu hati gelisah\nTerobati karena kehadiran dirimu.'),
('result', 'Pantun humor cinta', 'Pasar Banjar ada dikota\nPerginya belanja mempunyai uang saku\nBilanya kau di kejar cinta\nSembunyilah dalam hati aku.'),
('result', 'Pantun bertema kasmaran', 'Pergi ke Bali bertemu Bayu\nTidak lupa membeli pernak-pernik\nKalau memang kau pandai merayu\nCoba sana rayu gadis cantik.'),
('result', 'Pantun bertema kasmaran', 'Pergi ke pasar dengan naik unta\nBeli perhiasan dan intan permata\nTak peduli walau dia sudah tua\nYang penting adalah saling cinta.'),
('result', 'Pantun bertema situasi', 'Pergi tamasya ke Sumedang\nMelihat kambing makan rumput\nAnak-anak tertawa senang\nMelihat badut berjoget dangdut.'),
('result', 'Pantun jenaka pendidikan', 'Pergilah ke tepi kali\nJangan lupa bawa guci\nBangkitlah anak pertiwi\nBangunlah negerimu ini.'),
('result', 'Pantun lucu galau', 'Pohon salak pohon leci\nKalau tak disiram akan mati\nJanganlah kita selalu menanti\nKarena cinta tak harus memiliki.'),
('result', 'Pantun lucu galau', 'Pohon selasih tumbuh melata\nTumbuh perdu jauh di sana\nSepasang kekasih mabuk bercinta\nSiang merindu malam merana.'),
('result', 'Pantun jenaka anak anak', 'Prasasti di daun lontar\nAda kecap cap bango\nAda anak sok pintar\nDitanya planga-plongo.'),
('result', 'Pantun humor cinta', 'Radionya Di dalam di Pasar Slipi\nRawanya Buaya Pasarnya Cipaku\nTadinya dimalam ku bermimpi\nLuna Maya menjadi jodoh aku.'),
('result', 'Pantun kocak sindiran', 'Raja membangun satu dinasti\nJangan tersedia yang mencelakai\nLain di mulut lain di hati\nBerteman cuma melukai.'),
('result', 'Pantun bertema kehidupan', 'Sehabis manis sepah dibuang\nSehabis gelap terbitlah terang\nHabis uang jadilah ngutang\nTak sanggup bayar motor melayang.'),
('result', 'Pantun jenaka anak anak', 'Selalu menang tidak kalah\nKancil tetap menjadi juara\nPantun jenaka anak sekolah\nUntuk kelas empat kelas lima.'),
('result', 'Pantun lucu humor', 'Senin Selasa Rabu Kamis\nJumat Sabtu sampai Minggu\nEh ada gadis bermuka manis\nTapi ternyata itu hantu.'),
('result', 'Pantun humor romantis', 'Tak selalu jalan rata\nadakalanya berkelok tak rata\naku tak lihai merangkai kata\nnamun aku sanggup membuatmu cinta.'),
('result', 'Pantun kocak nasehat', 'Tidak baik menadah tangan\nselalu mengemis dipinggir jalan\napa gara-gara malasnya si insan\ntidak malu yang dia kerjakan.'),
('result', 'Pantun bertema kehidupan', 'Turun hujan rintik-tintik\nMemandang mendung di teras rumah\nHarap hati punya pacar cantik\nSyaratnya punya rumah dan mobil mewah.');
]
